# .gitguardian.yaml
# GitGuardian configuration for APTL security lab
# Only ignore specific paths with intentional test credentials

version: v1

# Ignore only CTF scenarios and qRadar license files
paths-ignore:
  - "scenarios/**"  # CTF scenarios with test credentials
  - "ctf/**"        # CTF scenarios with test credentials  
  - "files/*.key"   # qRadar license files