version: '3'

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kali-ctf
    volumes:
      - kali-shared:/shared
    networks:
      - ctf-network
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  ctf:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      - ctf-network
    restart: unless-stopped

networks:
  ctf-network:
    driver: bridge

volumes:
  kali-shared:
