"""Deterministic, resource-bounded evidence-bundle archive writer.

Uncompressed USTAR with normalized member metadata and members sorted by
bundle path, so two builds of the same members are byte-identical (EXP-008
preflight "Deterministic archive and separate transport"). Source members are
re-read no-follow and verified against their sealed digest/size; generated
members carry their own bytes. Output is placed OUTSIDE the input run tree and
published create-once via an owner-only candidate + hardlink — never
``tar.add(run_path)``, never a checksums file written back into the run.
"""

from __future__ import annotations

import hashlib
import os
import secrets
import tarfile
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path

from aptl.core.evidence_bundle import _io, codes
from aptl.core.evidence_bundle.errors import BundleError
from aptl.core.evidence_bundle.limits import DEFAULT_LIMITS, BundleLimits
from aptl.utils.deterministic_archive import deterministic_tarinfo, hash_file_nofollow

_MEMBER_MODE = 0o644
_FINAL_MODE = 0o400
_CANDIDATE_MODE = 0o600


@dataclass(frozen=True)
class BundleMember:
    """One archive member: exactly one of a run source path or generated bytes."""

    bundle_path: str
    digest: str
    size: int
    media_type: str
    source_run_relpath: str | None = None
    content: bytes | None = None


@dataclass(frozen=True)
class ArchiveResult:
    """Content identity of one published bundle archive."""

    archive_path: str
    digest: str
    size: int
    member_count: int


def _validate_bundle_path(path: str, limits: BundleLimits) -> None:
    if not path or path.startswith("/") or "\\" in path:
        raise BundleError(
            codes.REJECTED_SOURCE, f"bundle path is not a safe relative path: {path!r}"
        )
    if "\x00" in path or any(ord(ch) < 0x20 for ch in path):
        raise BundleError(
            codes.REJECTED_SOURCE, "bundle path contains control characters"
        )
    if len(path) > limits.max_path_length:
        raise BundleError(codes.REJECTED_SOURCE, "bundle path exceeds length limit")
    parts = path.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise BundleError(
            codes.REJECTED_SOURCE, f"bundle path has an unsafe component: {path!r}"
        )
    if len(parts) > limits.max_path_depth:
        raise BundleError(codes.REJECTED_SOURCE, "bundle path exceeds depth limit")


def _validate_members(members: list[BundleMember], limits: BundleLimits) -> None:
    if len(members) > limits.max_entries:
        raise BundleError(
            codes.REJECTED_SOURCE, "bundle exceeds the member entry limit"
        )
    seen: set[str] = set()
    total = 0
    for member in members:
        _validate_bundle_path(member.bundle_path, limits)
        if member.bundle_path in seen:
            raise BundleError(
                codes.REJECTED_SOURCE, f"duplicate bundle path: {member.bundle_path!r}"
            )
        seen.add(member.bundle_path)
        if (member.source_run_relpath is None) == (member.content is None):
            raise BundleError(
                codes.REJECTED_SOURCE,
                "member must have exactly one of a source path or generated content",
            )
        total += member.size
        if member.size > limits.max_member_bytes:
            raise BundleError(codes.REJECTED_SOURCE, "member exceeds the byte limit")
    if total > limits.max_total_bytes:
        raise BundleError(codes.REJECTED_SOURCE, "bundle exceeds the total byte limit")


def _prepare_parent(parent: Path) -> None:
    """Ensure the output parent is a private, owner-only directory.

    These bundles intentionally carry restricted evidence, so the directory that
    holds the in-flight candidate and the published archive must not be readable
    or searchable by other local accounts. An existing parent is accepted only
    when it is a real directory owned by the current user with no group/other
    permission bits; a missing one is created owner-only.
    """
    if parent.is_symlink():
        raise BundleError(
            codes.REJECTED_SOURCE, "bundle output parent must not be a symlink"
        )
    if parent.exists():
        if not parent.is_dir():
            raise BundleError(
                codes.REJECTED_SOURCE, "bundle output parent is not a directory"
            )
        info = parent.stat()
        if info.st_uid != os.geteuid():
            raise BundleError(
                codes.REJECTED_SOURCE,
                "bundle output parent is not owned by the current user",
            )
        if info.st_mode & 0o077:
            raise BundleError(
                codes.REJECTED_SOURCE, "bundle output parent is group/other accessible"
            )
    else:
        parent.mkdir(parents=True, exist_ok=True)
        parent.chmod(0o700)


def _resolve_output(run_dir: Path, output_path: Path) -> Path:
    out = Path(output_path)
    if out.exists() or out.is_symlink():
        raise BundleError(codes.REJECTED_SOURCE, "bundle output already exists")
    resolved = out.parent.resolve() / out.name
    run_resolved = run_dir.resolve()
    if resolved == run_resolved or run_resolved in resolved.parents:
        raise BundleError(
            codes.REJECTED_SOURCE, "bundle output must be outside the run tree"
        )
    _prepare_parent(out.parent)
    return resolved


def _member_bytes(run_dir: Path, member: BundleMember, limits: BundleLimits) -> bytes:
    if member.content is not None:
        data = member.content
    else:
        try:
            digest, size, data = _io.read_source(
                run_dir,
                member.source_run_relpath or "",
                max_bytes=limits.max_member_bytes,
            )
        except _io.SourceMissing as exc:
            raise BundleError(
                codes.MISSING_SOURCE, f"member source absent: {member.bundle_path}"
            ) from exc
        except _io.SourceRejected as exc:
            raise BundleError(
                codes.REJECTED_SOURCE, f"member source rejected: {exc.detail}"
            ) from exc
    actual = f"sha256:{hashlib.sha256(data).hexdigest()}"
    if actual != member.digest or len(data) != member.size:
        raise BundleError(
            codes.REJECTED_SOURCE,
            f"member disagrees with its sealed digest/size: {member.bundle_path}",
        )
    return data


def _write_tar(
    run_dir: Path, members: list[BundleMember], candidate: Path, limits: BundleLimits
) -> None:
    # Create the candidate through an exclusive, no-follow, mode-0600 descriptor
    # so its bytes are never exposed to other accounts under a permissive umask
    # and cannot be redirected through a pre-planted symlink.
    flags = os.O_CREAT | os.O_EXCL | os.O_WRONLY | os.O_NOFOLLOW | os.O_CLOEXEC
    try:
        fd = os.open(candidate, flags, _CANDIDATE_MODE)
    except OSError as exc:
        raise BundleError(
            codes.REJECTED_SOURCE, "bundle candidate could not be created"
        ) from exc
    try:
        with (
            os.fdopen(fd, "wb") as raw,
            tarfile.open(fileobj=raw, mode="w", format=tarfile.USTAR_FORMAT) as archive,
        ):
            for member in members:
                data = _member_bytes(run_dir, member, limits)
                info = deterministic_tarinfo(
                    member.bundle_path, is_dir=False, size=len(data), mode=_MEMBER_MODE
                )
                archive.addfile(info, BytesIO(data))
    except (OSError, tarfile.TarError) as exc:
        raise BundleError(
            codes.REJECTED_SOURCE, "bundle archive could not be assembled"
        ) from exc


def write_bundle_archive(
    run_dir: Path,
    output_path: Path,
    members: list[BundleMember],
    *,
    limits: BundleLimits = DEFAULT_LIMITS,
) -> ArchiveResult:
    """Write ``members`` into a deterministic uncompressed USTAR bundle.

    ``members`` are sorted by bundle path; source members are verified against
    their sealed digest/size while streaming. Raises :class:`BundleError` on a
    duplicate/unsafe path, a digest/size disagreement, an output under the run
    tree, or an already-existing output.
    """
    _validate_members(members, limits)
    ordered = sorted(members, key=lambda m: m.bundle_path)
    out = _resolve_output(run_dir, output_path)
    candidate = out.with_name(f".{out.name}.candidate-{secrets.token_hex(8)}")
    try:
        _write_tar(run_dir, ordered, candidate, limits)
        candidate.chmod(_FINAL_MODE)
        try:
            os.link(candidate, out, follow_symlinks=False)
        except FileExistsError as exc:
            raise BundleError(
                codes.REJECTED_SOURCE, "bundle output already exists"
            ) from exc
        digest, size = hash_file_nofollow(out)
        return ArchiveResult(
            archive_path=str(out), digest=digest, size=size, member_count=len(ordered)
        )
    finally:
        try:
            candidate.unlink(missing_ok=True)
        except OSError:
            pass


__all__ = ["BundleMember", "ArchiveResult", "write_bundle_archive"]
